### PR TITLE
Fix `SaveBlockStoreState` signature on `v0.38.x`

### LINKED ISSUE #2085: `SaveBlockStoreState` changed signature betweeon `v0.38.2` and `v0.38.3`
`SaveBlockStoreState` changed its signature from

```go
func SaveBlockStoreState(bsj *cmtstore.BlockStoreState, db dbm.DB)
```

to 

```go
func SaveBlockStoreStateBatch(bsj *cmtstore.BlockStoreState, batch dbm.Batch)
```

Since this function is public in this release, and `v0.38.3` is a point release, this function should not be changing

### PR DESCRIPTION
**Pull request by sergio-mena**
Closes #2085

Added `SaveBlockStoreStateBatch` with the new functionality, while leaving `SaveBlockStoreState` with the same signature as in `v0.38.2`

---

#### PR checklist

- [x] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Review by jmalicevic — APPROVED** [review]
LGTM

File: store/store.go [hunk 1]
```diff
@@ -611,12 +611,31 @@ func calcBlockHashKey(hash []byte) []byte {
 var blockStoreKey = []byte("blockStore")
 
 // SaveBlockStoreState persists the blockStore state to the database.
-func SaveBlockStoreState(bsj *cmtstore.BlockStoreState, batch dbm.Batch) {
+// depretaced: still present in this version for API compatibility
```
Comment (melekes) [inline store/store.go:614]: * deprecated
