### PR TITLE
indexer-respect-height-params-on-query

### LINKED ISSUE #1435: KV search by events ignores second height parameter if there is a event parameter
### Setup

**CometBFT version**: v0.37.2

**Have you tried the latest version**: no, but based on the code, the bug should be reproducible in the newest version as well.

**Environment**:
- **OS**: Ubuntu 22.04

### What happened?
I'm trying to query transactions using txSearch. I'm using three parameter: tx.height >= X AND tx.height <= Y and event.key = value. In this case the second tx.height is ignored. If event.key=value is missing then both tx.height params are respected.

### What did you expect to happen?
The query should respect all of the parameters.

### How to reproduce it
Add two transactions to the indexer. One should be at height X and the other - at height Y. Let's both transactions have an event with key "account" and value "number" equals "1". Making a query tx.height >= X AND tx.height <= Y-1 and account.number = 1 MUST return only the transaction at height X but now it returns both transactions.

### PR DESCRIPTION
**Pull request by kstoykov**
Closes #1435

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog`
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

File: state/indexer/query_range.go [hunk 1]
```diff
@@ -96,14 +96,13 @@ func (qr QueryRange) UpperBoundValue() interface{} {
 func LookForRangesWithHeight(conditions []syntax.Condition) (queryRange QueryRanges, indexes []int, heightRange QueryRange) {
 	queryRange = make(QueryRanges)
 	for i, c := range conditions {
-		heightKey := false
 		if IsRangeOperation(c.Op) {
+			heightKey := c.Tag == types.BlockHeightKey || c.Tag == types.TxHeightKey
```
Comment (jmalicevic) [inline state/indexer/query_range.go:100]: Sorry, I know this was my proposed change but maybe we can delete it from this line and just leave it as is (it will be set in line 106). I am worried I am missing a scenario where we set it here where for some reason the rest of the return values are not set and then there is some unexpected behaviour afterwards. 

The initial bug was due to always setting it to false in L99 (which we are not doing anymore). Do you mind verifying this makes sense?

Comment (kstoykov) [reply state/indexer/query_range.go:100]: To be honest, I didn't completely understand your solution initially. I just got that the heightKey check should be after the "if IsRangeOperaction(c.Op)". That's why I put it inside the check.

Based on my understanding of the code the "heightKey" must be TRUE only if the current processing operation is "height" or "block", otherwise it must be FALSE. That's why "heightKey" must be initialized on the beginning of each loop, because it is possible to process an operation that is not "heightKey". 

For example, if there are three operations - "height", "account.number", "height" then on first iteration the "heightKey" must be TRUE, then FALSE and finally TRUE again. Does it make sense or I'm missing something?

Comment (jmalicevic) [reply state/indexer/query_range.go:100]: Actually you are right. If you were to not set the `heightKey` every time, it would not set the `heightRange` values correctly. If it were not for that, and we needed to set only `queryRange` it would be fine. Your solution is good the way it is now, thank you for the clarifications. 

This indexer  code is quite tricky and has a bunch of corner cases so it is very easy to get lost in all the possibilities.

File: .changelog/unreleased/bug-fixes/1529-indexer-respect-height-params-on-query.md [hunk 2]
```diff
@@ -0,0 +1 @@
+- `[state/indexer]` Respect both height params while quering for events
```
Comment (jmalicevic) [inline .changelog/unreleased/bug-fixes/1529-indexer-respect-height-params-on-query.md:1]:
```suggestion
- `[state/indexer]` Respect both height params while querying for events
   ([\#1529](https://github.com/cometbft/cometbft/pull/1529))
```

**Review by jmalicevic — APPROVED** [review]
LGTM, thanks a lot for the effort! 

@thanethomson can you double check the changelog layout before we mark it as ok to merge.

**Comment by jmalicevic** [comment]
@kstoykov , can you please address the linting errors? Running `make lint` locally should give you a better idea where the errors are exactly.

**Comment by sergio-mena** [comment]
The linting errors are likely to be the ones we just fixed, so updating the PR branch to latest main should do

**Comment by jmalicevic** [comment]
> The linting errors are likely to be the ones we just fixed, so updating the PR branch to latest main should do

@kstoykov  as its your branch, I don't have permissions to merge into it... Its probably worth trying that first then before looking at the exact errors.

**Comment by kstoykov** [comment]
@jmalicevic I've merge main branch to my branch and there are no more lint errors so everything should be fine now.

**Comment by jmalicevic** [comment]
Thank you @kstoykov , tiggered a merge!
