### PR TITLE
fix(light): print an err if trusted store is empty

### LINKED ISSUE #3992: light: `runtime error: invalid memory address or nil pointer dereference`
### Setup
I'm on commit  `3323096bbb87d8722402f0a62a94b94589483097`
Getting a `Nil Pointer Dereference Error` when hitting the /block endpoint. This is also happing with other endpoints as well.
I have two validating nodes running locally and started the light client with:
```bash
./cometbft light 3636 -p "tcp://127.0.0.1:26657" -w "tcp://127.0.0.1:36657"
```

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
cb31aae24cf96b0aef918bf926680a67ea15ca76

**Have you tried the latest version**: yes/no
yes
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Reth Eth client
**Environment**:
- **OS** (e.g. from /etc/os-release):
 Macos 14.5 (23F79)
- **Install tools**:
- **Others**:

**node command runtime flags**:

### What happened?
Nil derefrence exception
### What did you expect to happen?
Return the latest light block
### Logs

Logs: 
```
I[2024-09-03|19:54:39.677] deprecated usage found in configuration file usage="[consensus.timeout_commit] is deprecated. Use `next_block_delay` in the ABCI `FinalizeBlockResponse`."
I[2024-09-03|19:54:39.677] Creating client...                           chainID=3636
I[2024-09-03|19:54:40.037] Starting proxy...                            laddr=tcp://localhost:8888
I[2024-09-03|19:54:40.046] serve                                        msg="Starting RPC HTTP server on 127.0.0.1:8888"
I[2024-09-03|19:55:02.662] VerifyHeader                                 height=1 hash=A55330FD41FB11793B5A737D7D5B9236A13D03C024642C401CD35B9E245C98EC
E[2024-09-03|19:55:02.664] panic in RPC HTTP handler                    err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 10 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1.2()\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:214 +0x557\npanic({0x4fd06c0?, 0x599a7e0?})\n\truntime/panic.go:770 +0x132\ngithub.com/cometbft/cometbft/light.(*Client).verifyLightBlock(0xc00015e6c0, {0x5158838, 0xc000180230}, 0xc00004ecc0, {0x275c7e08?, 0xede696096?, 0x0?})\n\tgithub.com/cometbft/cometbft/light/client.go:581 +0x22a\ngithub.com/cometbft/cometbft/light.(*Client).VerifyLightBlockAtHeight(0xc00015e6c0, {0x5158838, 0xc000180230}, 0x1, {0xc000482840?, 0x20?, 0x0?})\n\tgithub.com/cometbft/cometbft/light/client.go:492 +0xda\ngithub.com/cometbft/cometbft/light/rpc.(*Client).updateLightClientIfNeededTo(0xc00026e380, {0x5158838, 0xc000180230}, 0xc0000f6040)\n\tgithub.com/cometbft/cometbft/light/rpc/client.go:566 +0x6e\ngithub.com/cometbft/cometbft/light/rpc.(*Client).Block(0xc00026e380, {0x5158838, 0xc000180230}, 0x4?)\n\tgithub.com/cometbft/cometbft/light/rpc/client.go:330 +0x218\ngithub.com/cometbft/cometbft/light/proxy.RPCRoutes.makeBlockFunc.func10(0x0?, 0xc0000126f0)\n\tgithub.com/cometbft/cometbft/light/proxy/routes.go:110 +0x3a\nreflect.Value.call({0x4fe0360?, 0xc0002ee2b0?, 0x5140a00?}, {0x4c2c256, 0x4}, {0xc00018d6e0, 0x2, 0x2?})\n\treflect/value.go:596 +0xca6\nreflect.Value.Call({0x4fe0360?, 0xc0002ee2b0?, 0x4c30d6a?}, {0xc00018d6e0?, 0x5140a00?, 0xc0004822e0?})\n\treflect/value.go:380 +0xb9\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeHTTPHandler.func2({0x5153550, 0xc0003021b0}, 0xc0003d45a0)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_uri_handler.go:60 +0x4c5\nnet/http.HandlerFunc.ServeHTTP(0xc0001108f0?, {0x5153550?, 0xc0003021b0?}, 0x4f7b280?)\n\tnet/http/server.go:2171 +0x29\nnet/http.(*ServeMux).ServeHTTP(0xd?, {0x5153550, 0xc0003021b0}, 0xc0003d45a0)\n\tnet/http/server.go:2688 +0x1ad\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.defaultHandler.ServeHTTP(...)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:262\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x51533f0, 0xc000398a80}, 0xc0003d45a0)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:237 +0x228\nnet/http.HandlerFunc.ServeHTTP(0x514b718?, {0x51533f0?, 0xc000398a80?}, 0x4f53980?)\n\tnet/http/server.go:2171 +0x29\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.PreChecksHandler.func2({0x51533f0, 0xc000398a80}, 0xc0003d45a0)\n\tgithub.com/cometbft/cometbft/rpc/jsonrpc/server/http_server.go:327 +0x10c\nnet/http.HandlerFunc.ServeHTTP(0x415ea99?, {0x51533f0?, 0xc000398a80?}, 0xc00017cb68?)\n\tnet/http/server.go:2171 +0x29\nnet/http.serverHandler.ServeHTTP({0xc00018d350?}, {0x51533f0?, 0xc000398a80?}, 0x6?)\n\tnet/http/server.go:3142 +0x8e\nnet/http.(*conn).serve(0xc0000d0090, {0x5158800, 0xc000473a40})\n\tnet/http/server.go:2044 +0x5e8\ncreated by net/http.(*Server).Serve in goroutine 1\n\tnet/http/server.go:3290 +0x4b4\n"

``` 

### `dump_consensus_state` output

```json
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "round_state": {
      "height": "2786",
      "round": 0,
      "step": 1,
      "start_time": "2024-09-03T20:00:05.85179Z",
      "commit_time": "2024-09-03T20:00:04.85179Z",
      "validators": {
        "validators": [
          {
            "address": "009D915D631DB0A3FEFB32685779D023153698DB",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "AqSCYUYNrmyoGL6j6o3cKRt63fzpdv+LB3guvIdCNziU"
            },
            "voting_power": "10",
            "proposer_priority": "0"
          },
          {
            "address": "09784D2BAA503337EAB2B1B023296324BA4827A6",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "A9XFfycX13DcZWZHWTSoTA8Yu6Cappw0U7Ji5hbD8l5V"
            },
            "voting_power": "10",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "09784D2BAA503337EAB2B1B023296324BA4827A6",
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "A9XFfycX13DcZWZHWTSoTA8Yu6Cappw0U7Ji5hbD8l5V"
          },
          "voting_power": "10",
          "proposer_priority": "0"
        }
      },
      "proposal": null,
      "proposal_receive_time": "0001-01-01T00:00:00Z",
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": -1,
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": -1,
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": 0,
          "prevotes": [
            "nil-Vote",
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{2:__} 0/20 = 0.00",
          "precommits": [
            "nil-Vote",
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{2:__} 0/20 = 0.00"
        }
      ],
      "commit_round": -1,
      "last_commit": {
        "votes": [
          "Vote{0:009D915D631D 2785/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 60663836B00C A59A51ADA7DF B896886E109B @ 2024-09-03T20:00:04.830052Z}",
          "Vote{1:09784D2BAA50 2785/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 60663836B00C ADDF300C714D B896886E109B @ 2024-09-03T20:00:04.781122Z}"
        ],
        "votes_bit_array": "BA{2:xx} 20/20 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "009D915D631DB0A3FEFB32685779D023153698DB",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "AqSCYUYNrmyoGL6j6o3cKRt63fzpdv+LB3guvIdCNziU"
            },
            "voting_power": "10",
            "proposer_priority": "-10"
          },
          {
            "address": "09784D2BAA503337EAB2B1B023296324BA4827A6",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "A9XFfycX13DcZWZHWTSoTA8Yu6Cappw0U7Ji5hbD8l5V"
            },
            "voting_power": "10",
            "proposer_priority": "10"
          }
        ],
        "proposer": {
          "address": "009D915D631DB0A3FEFB32685779D023153698DB",
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "AqSCYUYNrmyoGL6j6o3cKRt63fzpdv+LB3guvIdCNziU"
          },
          "voting_power": "10",
          "proposer_priority": "-10"
        }
      },
      "triggered_timeout_precommit": false
    },
    "peers": [
      {
        "node_address": "331616cba520bff2bcfa3efbe748a044d9ec3c08@127.0.0.1:36656",
        "peer_state": {
          "round_state": {
            "height": "2786",
            "round": 0,
            "step": 1,
            "start_time": "2024-09-03T20:00:05.044835Z",
            "proposal": false,
            "proposal_block_part_set_header": {
              "total": 0,
              "hash": ""
            },
            "proposal_block_parts": null,
            "proposal_pol_round": -1,
            "proposal_pol": "__",
            "prevotes": "__",
            "precommits": "__",
            "last_commit_round": 0,
            "last_commit": "xx",
            "catchup_commit_round": -1,
            "catchup_commit": "__"
          },
          "stats": {
            "votes": "580",
            "block_parts": "145"
          }
        }
      }
    ]
  }
}

```

### PR DESCRIPTION
**Pull request by melekes**
```
E[2024-09-04|08:30:08.839] Cannot start the light client from an empty trusted store. Please provide either an initialized trusted store, using the `--home-dir` flag, or trusted information to bootstrap the trusted store, via `--hash` and `--height` flags.
ERROR: trusted store is empty
```

Refs #3992

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

File: light/client.go [hunk 1]
```diff
@@ -268,16 +264,16 @@ func (c *Client) restoreTrustedLightBlock() error {
...
 	}
-
-	if lastHeight > 0 {
-		trustedBlock, err := c.trustedStore.LightBlock(lastHeight)
-		if err != nil {
-			return ErrGetTrustedBlock{Err: err}
-		}
-		c.latestTrustedBlock = trustedBlock
-		c.logger.Info("Restored trusted light block", "height", lastHeight)
+	if lastHeight == -1 {
```
Comment (cason) [inline light/client.go:267]: So, when the store is empty, `LastLightBlockHeight()` returns `-1, nil`.

File: light/client.go [hunk 2]
```diff
@@ -268,16 +264,16 @@ func (c *Client) restoreTrustedLightBlock() error {
...
+		return ErrEmptyTrustedStore
 	}
 
+	trustedBlock, err := c.trustedStore.LightBlock(lastHeight)
```
Comment (cason) [inline light/client.go:271]: Did you test using `lastHeight == 0`? This situation is covered in the original version.

File: light/client.go [hunk 3]
```diff
@@ -185,7 +185,7 @@ func NewClient(
 	}
 
 	c, err := NewClientFromTrustedStore(chainID, trustOptions.Period, primary, witnesses, trustedStore, options...)
-	if err != nil {
+	if err != nil && !errors.Is(err, ErrEmptyTrustedStore) {
```
Comment (cason) [inline light/client.go:188]: Why we are lenient with an empty trusted store?

File: light/client_test.go [hunk 4]
```diff
@@ -905,6 +905,27 @@ func TestClient_NewClientFromTrustedStore(t *testing.T) {
...
+	c, err := light.NewClientFromTrustedStore(
+		chainID,
+		trustPeriod,
+		fullNode,
+		[]provider.Provider{fullNode},
+		db,
+	)
+
+	if err != nil {
+		assert.Error(t, err)
```
Comment (cason) [inline light/client_test.go:921]: You know this only checks that `err != nil` like in the previous line, right?

File: cmd/cometbft/commands/light.go [hunk 5]
```diff
@@ -197,6 +197,9 @@ func runProxy(_ *cobra.Command, args []string) error {
 		)
 	}
 	if err != nil {
+		if errors.Is(err, light.ErrEmptyTrustedStore) {
```
Comment (cason) [inline cmd/cometbft/commands/light.go:200]: This can only happen in the `else` clause above, am I wrong?

File: cmd/cometbft/commands/light.go [hunk 6]
```diff
@@ -197,6 +197,9 @@ func runProxy(_ *cobra.Command, args []string) error {
...
+			logger.Error("Wanted to start from trusted store but it was empty. Please provide a trusted `--hash` and `--height` or check `--home-dir`.")
```
Comment (cason) [inline cmd/cometbft/commands/light.go:201]: Suggestion for the message.

"Starting the light client from an empty trusted store. Please provide an initialized trusted store, using the `---home-dir` flag, or provide trusted information to bootstrap the trusted store, via `--hash` and `--height` flags."

File: .changelog/unreleased/bug-fixes/3992-light-panic.md [hunk 7]
```diff
@@ -0,0 +1,4 @@
+- `[light]` Print an error if starting from the trusted store, but it's empty
```
Comment (cason) [inline .changelog/unreleased/bug-fixes/3992-light-panic.md:1]:
```suggestion
- `[light]` Return and log an error when starting from an empty trusted store.
```

File: .changelog/unreleased/bug-fixes/3992-light-panic.md [hunk 8]
```diff
@@ -0,0 +1,4 @@
...
+  (due to incorrect configuration or user forgetting to provide a trusted
```
Comment (cason) [inline .changelog/unreleased/bug-fixes/3992-light-panic.md:2]:
```suggestion
  This can happen using the `light` CometBFT command-line command while using a fresh trusted store and no trusted height and hash are provided.
```

**Review by cason — COMMENTED** [review]
This appears to solve the issue, left some comments.

File: .changelog/unreleased/bug-fixes/3992-light-panic.md [hunk 9]
```diff
@@ -0,0 +1,4 @@
+- `[light]` Return and log an error when starting from an empty trusted store.
+  This can happen using the `light` CometBFT command-line command while using a fresh trusted store and no trusted height and hash are provided.
+  height and hash arguments).
```
Comment (cason) [inline .changelog/unreleased/bug-fixes/3992-light-panic.md:3]: I forgot to remove this remaining line.

File: light/client.go (hunk 3 above)
Comment (melekes) [reply light/client.go:188]: because we're bootstrapping the state using hash and height here in case trusted store is empty

File: light/client.go (hunk 1 above)
Comment (melekes) [reply light/client.go:267]: yes

File: light/client_test.go (hunk 4 above)
Comment (melekes) [reply light/client_test.go:921]: I can't assert the type because you've asked me to write a test that works for both `main` and this PR.

File: light/client_test.go [hunk 10]
```diff
@@ -905,6 +905,25 @@ func TestClient_NewClientFromTrustedStore(t *testing.T) {
...
+		fullNode,
+		[]provider.Provider{fullNode},
+		db,
+	)
+
+	if err == nil {
+		assert.NotPanics(t, func() {
+			_, _ = c.VerifyLightBlockAtHeight(ctx, 2, bTime)
+		})
+	}
```
Comment (cason) [inline light/client_test.go:924]: You had a test that checked the error type before.

File: light/client_test.go [hunk 11]
```diff
@@ -905,6 +905,25 @@ func TestClient_NewClientFromTrustedStore(t *testing.T) {
 	assert.EqualValues(t, l1.Height, h.Height)
 }
 
+func TestClient_NewClientFromTrustedStore2(t *testing.T) {
```
Comment (cason) [inline light/client_test.go:908]:
```suggestion
func TestClient_NewClientFromEmptyTrustedStore(t *testing.T) {
```

**Review by cason — APPROVED** [review]
Legit.

File: light/client_test.go (hunk 10 above)
Comment (cason) [reply light/client_test.go:924]: `require.ErrorIs(t, err, light.ErrEmptyTrustedStore)`
