### PR TITLE
The store DB and the companion `BlockStore` struct are sometimes out of sync

### LINKED ISSUE #1854: e2e are failing on `main`, `v1.x`, and `v0.38.x`
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):

`main`, `v1.x`, and `v0.38.x`

**Have you tried the latest version**: yes

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

e2e app

**Environment**: N/A (reproed on OSX and Debian)

**node command runtime flags**:

N/A (using e2e infra, with `networks/simple.toml` to repro

### Config

N/A (according to manifest file `networks/simple.toml`)

### What happened?

The faulure is not deterministic, it's a race condition.
Tests fail with a panic (trying to access a `nil` block:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0xbb160c]

goroutine 55 [running]:
testing.tRunner.func1.2({0xc5e1c0, 0x1510be0})
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x397
panic({0xc5e1c0?, 0x1510be0?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x21f
github.com/cometbft/cometbft/test/e2e/tests_test.TestApp_Hash.func1(_, {{0xc0000f7ef9, 0xb}, {0xd765df, 0x1f}, 0xc0003146c0, {0xc000501680, 0x9}, {0xf5ec10, 0xc0000b0d80}, ...})
	/home/runner/work/cometbft/cometbft/test/e2e/tests/app_test.go:61 +0x2cc
github.com/cometbft/cometbft/test/e2e/tests_test.testNode.func1(0x0?)
	/home/runner/work/cometbft/cometbft/test/e2e/tests/e2e_test.go:60 +0x7e
testing.tRunner(0xc00040f520, 0xc0000b12a8)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 16
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad
FAIL	github.com/cometbft/cometbft/test/e2e/tests	1.534s
FAIL
E[2023-12-16|02:13:40.478] exit status 1
```

### What did you expect to happen?

e2e tests should pass

### How to reproduce it

Use this simplistic patch to run e2e tests on `network/simple.toml`:

```
diff --git a/test/e2e/tests/app_test.go b/test/e2e/tests/app_test.go
index d4f0f9156..2e4d985b1 100644
--- a/test/e2e/tests/app_test.go
+++ b/test/e2e/tests/app_test.go
@@ -36,6 +36,7 @@ func TestApp_InitialState(t *testing.T) {
 // Tests that the app hash (as reported by the app) matches the last
 // block and the node sync status.
 func TestApp_Hash(t *testing.T) {
+       for i := 0; i < 200; i++ {
                testNode(t, func(t *testing.T, node e2e.Node) {
                        client, err := node.Client()
                        require.NoError(t, err)
@@ -61,6 +62,7 @@ func TestApp_Hash(t *testing.T) {
                                fmt.Sprintf("%x", block.Block.AppHash.Bytes()),
                                "app hash does not match last block's app hash")
                })
+       }
 }

 // Tests that we can set a value and retrieve it.
```

### Logs

See above for backtrace

### `dump_consensus_state` output

N/A

### Anything else we need to know

The bug has been triaged by bisecting `v0.38.x` and `main` with the reproduction patch. The PR identified by the bisect is #1755 (and its backports)

### PR DESCRIPTION
**Pull request by sergio-mena**
Closes #1854

The `e2e` tests have been failing often (but not deterministically) for a few days. After investigation, the root cause was identified from the subtle changes in the logic introduced by DB batching in #1755 (which otherwise is a very much needed PR).

The problem shows up as a race condition, so it is subtle to see why this happened and to review it effectively. This has led me to follow a process similar to #539 to first show how to repro it, and then show that the fix works. So, please pay attention to the little ❌ or ✅ next to each commit below (you can click and check how the e2e tests failed/passed).

* Commit#1: change e2e logic to allow for repro -- this could repro the problem locally but couldn't repro it on CI 👎 
* Commit#2: adding a `time.Sleep` (5 seconds) at the "right place" -- 2nd repro attempt (it worked! 👍, ignore the unit tests failing; only `e2e` run is relevant here)
* Commit#3: tune parameters of `TestApp_Hash` to be able to repro (or not) within a reasonable time (again, ignore unit tests) -- `e2e` still failing
* Commit#4: the fix, still with the added `time.Sleep`. Don't get fooled by the ❌; if you click on it, the e2e tests are now ✅
* Commit#5: revert commit#1 and commit#3; remove the `time.Sleep` added in commit#2. The PR has now the code to merge
* Further commits: addressing comments

No changelog needed as this started being a problem a few days ago.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

File: internal/store/store.go [hunk 1]
```diff
@@ -42,9 +42,13 @@ The store can be assumed to contain all contiguous blocks between base and heigh
...
-	// mtx guards access to the struct fields listed below it. We rely on the database to enforce
-	// fine-grained concurrency control for its data, and thus this mutex does not apply to
-	// database contents. The only reason for keeping these fields in the struct is that the data
+	// mtx guards access to the struct fields listed below it. Although we rely on the database
+	// to enforce fine-grained concurrency control for its data, we need to make sure that
+	// no external observer can get data from the database that is not in sync with the fields below,
+	// and vice-versa. Hence, when updating the fields below, we use the mutex to make sure
+	// that the database is also up to date. This prevents any concurrent external access from
+	// obtaining inconsistent data.
+	// The only reason for keeping these fields in the struct is that the data
```
Comment (melekes) [inline internal/store/store.go:51]: Note: https://github.com/cometbft/cometbft/pull/1814 will solve this

**Review by melekes — APPROVED** [review]

File: internal/store/store.go [hunk 2]
```diff
@@ -325,16 +329,10 @@ func (bs *BlockStore) PruneBlocks(height int64, state sm.State) (uint64, int64,
 		// We can't trust batches to be atomic, so update base first to make sure no one
 		// tries to access missing blocks.
 		bs.mtx.Lock()
+		defer bs.mtx.Unlock()
+		defer batch.Close()
 		bs.base = base
```
Comment (lasarojc) [inline internal/store/store.go:334]:
```suggestion
		defer batch.Close()
		defer bs.mtx.Unlock()
		bs.base = base
```

**Review by lasarojc — APPROVED** [review]
