### PR TITLE
Backport of PR #771 to 0.34 : big int parsing

### LINKED ISSUE #726: Using pubsub query with big values results in an int64 overflow
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): should be latest

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Rebus

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Install tools**:
- **Others**:

**node command runtime flags**:

### What happened?

I am building a tool to subscribe to transactions and messages I need. Internally I use Query /libs/pubsub/query/query.go to filter out messages I do not need. One of my goals is to use values comparison (for example, as in this filter: delegate.amount > 10000000, to filter out MsgDelegate messages with amount less than 10m native tokens). It works okay with small values, but on chains with a different denom exponent (namely, Rebus, with exponent 18, and probably Evmos (haven't tested it with it, but it should result in a similar error)), when trying to subscribe to that filter, it would result in the following error:

```
7:52PM ERR Error querying for events err="failed to match against query message.action = '/cosmos.staking.v1beta1.MsgDelegate' AND delegate.amount > 10000000000000000000: got strconv.ParseInt: parsing \"10000000000000000000\": value out of range while trying to parse 10000000000000000000 as int64 (should never happen if the grammar is correct)" module=pubsub server=node
```

And if you do the same in app (try to create a filter from the following string and use query.Matches() on it, it would result in the error in this app.

### What did you expect to happen?

 Conversion is done without any errors.

### How to reproduce it

- Start a Rebus node (or any other node that has denom exponent 18 or bigger)
- Subscribe via Tendermint Websockets to the updates on the following filter: `message.action = '/cosmos.staking.v1beta1.MsgDelegate' AND delegate.amount > 10000000000000000000`
- Check logs and see errors if such transactions would occur, get a message like the one above per each.

### Logs

See above

### Anything else we need to know

This is a copy of https://github.com/tendermint/tendermint/issues/9978 which was closed as stale but apparently never fixed.

### PR DESCRIPTION
**Pull request by jmalicevic**
Closes #726  for 0.34.x

This is a manual backport of #771  because Mergify did not trigger it.

### CODE REVIEW

File: state/indexer/block/kv/kv_test.go [hunk 1]
```diff
@@ -358,3 +358,132 @@ func TestBlockIndexerMulti(t *testing.T) {
 		})
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv_test.go:358]: There were some test cases removed from the this test in the original patch. Any reason for them to stay here?

File: state/indexer/block/kv/util.go [hunk 2]
```diff
@@ -135,7 +136,7 @@ func parseEventSeqFromEventKey(key []byte) (int64, error) {
 func lookForHeight(conditions []query.Condition) (int64, bool, int) {
 	for i, c := range conditions {
 		if c.CompositeKey == types.BlockHeightKey && c.Op == query.OpEqual {
-			return c.Operand.(int64), true, i
+			return c.Operand.(*big.Int).Int64(), true, i
```
Comment (sergio-mena) [inline state/indexer/block/kv/util.go:139]: This change in not present in `v0.37.x`, do we know why?

File: state/indexer/block/kv/util.go [hunk 3]
```diff
@@ -196,7 +197,7 @@ func dedupMatchEvents(conditions []query.Condition) ([]query.Condition, bool) {
 	for i, c := range conditions {
 		if c.CompositeKey == types.MatchEventKey {
 			// Match events should be added only via RPC as the very first query condition
-			if i == 0 && c.Op == query.OpEqual && c.Operand.(int64) == 1 {
+			if i == 0 && c.Op == query.OpEqual && c.Operand.(*big.Int).Int64() == 1 {
```
Comment (sergio-mena) [inline state/indexer/block/kv/util.go:200]: Same here, this does not appear in the `v0.37.x` version of the patch, do we know the reason?

File: state/txindex/kv/kv.go [hunk 4]
```diff
@@ -349,7 +350,7 @@ func lookForHash(conditions []query.Condition) (hash []byte, ok bool, err error)
 func lookForHeight(conditions []query.Condition) (height int64, heightIdx int) {
 	for i, c := range conditions {
 		if c.CompositeKey == types.TxHeightKey && c.Op == query.OpEqual {
-			return c.Operand.(int64), i
+			return c.Operand.(*big.Int).Int64(), i
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:353]: Change no present in `v0.37.x`, reason?

File: state/txindex/kv/utils.go [hunk 5]
```diff
@@ -33,7 +34,7 @@ func dedupMatchEvents(conditions []query.Condition) ([]query.Condition, bool) {
 	for i, c := range conditions {
 		if c.CompositeKey == types.MatchEventKey {
 			// Match events should be added only via RPC as the very first query condition
-			if i == 0 && c.Op == query.OpEqual && c.Operand.(int64) == 1 {
+			if i == 0 && c.Op == query.OpEqual && c.Operand.(*big.Int).Int64() == 1 {
```
Comment (sergio-mena) [inline state/txindex/kv/utils.go:37]: Not in `v0.37.x`, reason?

**Review by sergio-mena — COMMENTED** [review]
Only minor comments on `v0.34.x` <--> `v0.37.x` discrepancies. I'm interested in the reasons for those

File: .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md [hunk 6]
```diff
@@ -0,0 +1,2 @@
+- `[state/kvindex]` Querying event attributes that are bigger than int64 is now enabled. We are not supporting reading floats from the db into the indexer  nor parsing them into BigFloats to not introduce breaking changes in minor releases.
```
Comment (lasarojc) [inline .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md:1]:
```suggestion
- `[state/kvindex]` Querying event attributes that are bigger than int64 is now enabled. We are not supporting reading floats from the db into the indexer nor parsing them into BigFloats to not introduce breaking changes in minor releases.
```

File: docs/app-dev/indexing-transactions.md [hunk 7]
```diff
@@ -267,3 +267,10 @@ is ignored and the data is retrieved as if `match_events=false`.
 Additionally, if a node that was running Tendermint Core 
 when the data was first indexed, and switched to CometBFT, is queried, it will retrieve this previously indexed
 data as if `match_events=false` (attributes can match the query conditions across different events on the same height).
+# Event attribute value types
```
Comment (lasarojc) [inline docs/app-dev/indexing-transactions.md:270]:
```suggestion

# Event attribute value types

```

File: docs/app-dev/indexing-transactions.md [hunk 8]
```diff
@@ -267,3 +267,10 @@ is ignored and the data is retrieved as if `match_events=false`.
...
+Users can use anything as an event value. However, if the even attrbute value is a number, the following restrictions apply:
+- Negative numbers will not be properly retrieved when querying the indexer
```
Comment (lasarojc) [inline docs/app-dev/indexing-transactions.md:272]:
```suggestion
Users can use anything as an event value. However, if the event attribute value is a number, the following restrictions apply:

- Negative numbers will not be properly retrieved when querying the indexer
```

File: docs/app-dev/indexing-transactions.md [hunk 9]
```diff
@@ -267,3 +267,10 @@ is ignored and the data is retrieved as if `match_events=false`.
...
+- When querying the events using `tx_search` and `block_search`, the value given as part of the condition cannot be a float.
+- Any event value retrieved from the database will be represented as a `BigInt` (from `math/big`)
+- Floating point values are not read from the database even with the introduction of `BigInt`. This was intentionally done
```
Comment (lasarojc) [inline docs/app-dev/indexing-transactions.md:275]: note to self: not read or read as int?

File: docs/core/subscription.md [hunk 10]
```diff
@@ -40,6 +40,20 @@ You can also use tags, given you had included them into DeliverTx
...
+## Query parameter and event type restrictions
+
+While CometBFT imposes no restrictions on the application with regards to the type of 
+the event output, there are several restrictions when it comes to querying 
+events whose attribute values are numeric. 
+
+- Queries cannot include negative numbers
+- If floating points are compared to integers, they are converted to an integer
+- Floating point to floating point comparison leads to a loss of precision for very big floating point numbers
+(`10000000000000000000.0` is treated the same as `10000000000000000000.6`)
```
Comment (lasarojc) [inline docs/core/subscription.md:53]:
```suggestion
(e.g., `10000000000000000000.0` is treated the same as `10000000000000000000.6`) 
```

File: docs/core/subscription.md [hunk 11]
```diff
@@ -40,6 +40,20 @@ You can also use tags, given you had included them into DeliverTx
...
+
+While CometBFT imposes no restrictions on the application with regards to the type of 
+the event output, there are several restrictions when it comes to querying 
+events whose attribute values are numeric. 
+
+- Queries cannot include negative numbers
+- If floating points are compared to integers, they are converted to an integer
+- Floating point to floating point comparison leads to a loss of precision for very big floating point numbers
+(`10000000000000000000.0` is treated the same as `10000000000000000000.6`) 
+- When floating points do get converted to integers, they are not rounded, the decimal part is simply truncated.
```
Comment (lasarojc) [inline docs/core/subscription.md:54]:
```suggestion
- When floating points do get converted to integers, they are always rounded down.
```

File: libs/pubsub/query/query.go [hunk 12]
```diff
@@ -151,16 +152,18 @@ func (q *Query) Conditions() ([]Condition, error) {
 
 				conditions = append(conditions, Condition{eventAttr, op, value})
 			} else {
-				value, err := strconv.ParseInt(number, 10, 64)
-				if err != nil {
-					err = fmt.Errorf(
-						"got %v while trying to parse %s as int64 (should never happen if the grammar is correct)",
-						err, number,
+				valueBig := new(big.Int)
+
```
Comment (lasarojc) [inline libs/pubsub/query/query.go:156]:
```suggestion
```

File: libs/pubsub/query/query.go [hunk 13]
```diff
@@ -298,11 +301,13 @@ func (q *Query) Matches(events map[string][]string) (bool, error) {
...
 				}
 			} else {
-				value, err := strconv.ParseInt(number, 10, 64)
-				if err != nil {
-					err = fmt.Errorf(
-						"got %v while trying to parse %s as int64 (should never happen if the grammar is correct)",
-						err, number,
+				value := new(big.Int)
+				_, ok := value.SetString(number, 10)
+
```
Comment (lasarojc) [inline libs/pubsub/query/query.go:306]:
```suggestion
```

File: libs/pubsub/query/query.go [hunk 14]
```diff
@@ -451,42 +456,59 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
+				// Here we are simulating the behavior that int64(floatValue). This was the default behavior
+				// before introducing BigInts and we do not want to break the logic in minor releases.
+				_, ok := v.SetString(strings.Split(filteredValue, ".")[0], 10)
+				if !ok {
+					return false, fmt.Errorf("failed to convert value %s from float to big int", filteredValue)
+				}
+			} else {
+				// try our best to convert value from tags to big int
+				_, ok := v.SetString(filteredValue, 10)
+
```
Comment (lasarojc) [inline libs/pubsub/query/query.go:491]: Removing these empty lines for consistency with other lines in the change. I am fine with another standard.

```suggestion
```

File: libs/pubsub/query/query.go [hunk 15]
```diff
@@ -451,42 +456,59 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
-			v = int64(v1)
-		} else {
-			var err error
-			// try our best to convert value from tags to int64
-			v, err = strconv.ParseInt(filteredValue, 10, 64)
-			if err != nil {
-				return false, fmt.Errorf("failed to convert value %v from event attribute to int64: %w", filteredValue, err)
 			}
-		}
+			cmpRes := operandVal.Cmp(v)
```
Comment (lasarojc) [inline libs/pubsub/query/query.go:497]: If you invert it here

```suggestion
			cmpRes := v.Cmp(operandVal)
```

then ...

File: libs/pubsub/query/query.go [hunk 16]
```diff
@@ -451,42 +456,59 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
+			case OpLessEqual:
+				return cmpRes == 0 || cmpRes == 1, nil
+			case OpGreaterEqual:
+				return cmpRes == 0 || cmpRes == -1, nil
+			case OpLess:
+				return cmpRes == 1, nil
+			case OpGreater:
+				return cmpRes == -1, nil
+			case OpEqual:
+				return cmpRes == 0, nil
```
Comment (lasarojc) [inline libs/pubsub/query/query.go:508]: then you can make the parameter match the comparison

```suggestion
			case OpLessEqual:
				return cmpRes <= 0, nil
			case OpGreaterEqual:
				return cmpRes >= 0, nil
			case OpLess:
				return cmpRes < 0, nil
			case OpGreater:
				return cmpRes > 0 , nil
			case OpEqual:
				return cmpRes == 0, nil
```

File: docs/app-dev/indexing-transactions.md (hunk 9 above)
Comment (jmalicevic) [reply docs/app-dev/indexing-transactions.md:275]: Not read at all, they are simply ignored because the conversion to `BigInt` fails.

File: state/indexer/block/kv/kv_test.go (hunk 1 above)
Comment (jmalicevic) [reply state/indexer/block/kv/kv_test.go:358]: The reason they are here is because in 0.34 we have two tests for the same query - one with `match.events`, and one without. In 0.37 they were left over and hence deleted. Here we need both.

File: state/indexer/block/kv/util.go (hunk 2 above)
Comment (jmalicevic) [reply state/indexer/block/kv/util.go:139]: Because  the function `lookForHeight` is not used at all, we use only `dedupHeight`. In 0.34.x we still keep the old behaviour hence using this function.

File: state/indexer/block/kv/util.go (hunk 3 above)
Comment (jmalicevic) [reply state/indexer/block/kv/util.go:200]: 0.37.x does not have `match.events`, hence no `dedupMatchEvents` function.

File: state/txindex/kv/kv.go (hunk 4 above)
Comment (jmalicevic) [reply state/txindex/kv/kv.go:353]: Same as above.

File: state/txindex/kv/utils.go (hunk 5 above)
Comment (jmalicevic) [reply state/txindex/kv/utils.go:37]: Same as for `dedupMatchEvents` in the block indexer.

File: libs/pubsub/query/query.go (hunk 16 above)
Comment (jmalicevic) [reply libs/pubsub/query/query.go:505]: Yes, the old logic was a bit twisted. I can test this, I was just not sure whether to mess with this at all :)

Comment (lasarojc) [reply libs/pubsub/query/query.go:505]: no worries. Not a requirement for approval, since it is correct.

Comment (sergio-mena) [reply libs/pubsub/query/query.go:505]: As this is a backport, I'd lean toward not much refactoring

**Review by sergio-mena — APPROVED** [review]
LGTM.
Please make sure you address @lasarojc's comments

File: libs/pubsub/query/query.go (hunk 16 above)
Comment (jmalicevic) [reply libs/pubsub/query/query.go:505]: @lasarojc let me know if its fine with you to leave it and whether the other changes make sense :)

File: .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md [hunk 17]
```diff
@@ -0,0 +1,2 @@
+- `[state/kvindex]` Querying event attributes that are bigger than int64 is now enabled. We are not supporting reading floats from the db into the indexer nor parsing them into BigFloats to not introduce breaking changes in minor releases.
+  ([\#771](https://github.com/cometbft/cometbft/pull/771))
```
Comment (thanethomson) [inline .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md:2]: > Querying event attributes that are bigger than int64 is now enabled.

This makes sense to me as something to communicate to users.

> We are not supporting reading floats from the db into the indexer nor parsing them into BigFloats to not introduce breaking changes in minor releases.

What does this, however, mean for users?

Comment (jmalicevic) [reply .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md:2]: Maybe this does not have to be in the changelog, but only in the docs. This is basically the same behaviour as they had before, but they might have been unaware of this. I agree that maybe this should be removed frm the changelog but left in the docs.

File: libs/pubsub/query/query.go (hunk 16 above)
Comment (lasarojc) [reply libs/pubsub/query/query.go:505]: not needed. resolving.

**Review by lasarojc — APPROVED** [review]

**Comment by jmalicevic** [comment]
@thanethomson , I am closing this as the content is in the docs, but feel free to ping me to change the changelog message.
