### PR TITLE
Fill `time` field in `ExecCommitBlock`

### LINKED ISSUE #739: `ExecCommitBlock` does not fill the time field in `FinalizeBlock`
## Bug Report

Related to #687

`ExecCommitBlock` does not fill the time field in `FinalizeBlock`

### Setup

**CometBFT version** : `main` and `v0.38.x`

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
N/A

**Environment**:
N/A

**node command runtime flags**:
N/A

### Config

N/A

### What happened?

`ExecCommitBlock` does not fill the time field in `FinalizeBlock`. This shows up when replaying blocks

### What did you expect to happen?

`ExecCommitBlock` must fill the time field in `FinalizeBlock`

### How to reproduce it

TODO

### Logs

N/A

### `dump_consensus_state` output

N/A

### Anything else we need to know

Patch available.

Thanks again to @ze97286 for catching this

### PR DESCRIPTION
**Pull request by sergio-mena**
Closes #739

Similar to #687, `ExecCommitBlock` is not filling the `time` field. Further, there was no UT catching this.
This PR add logic to an existing test case to check for that field. The test case is initially failing. When added the production fix (and fixing the test case logic), the test case passes.

---

#### PR checklist

- [x] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

File: state/execution_test.go [hunk 1]
```diff
@@ -206,10 +206,11 @@ func TestFinalizeBlockValidators(t *testing.T) {
 		desc                     string
 		lastCommitSigs           []types.ExtendedCommitSig
 		expectedAbsentValidators []int
+		shouldHaveTs             bool
```
Comment (thanethomson) [inline state/execution_test.go:209]: The linter's complaining about this field name - is the "Ts" meant to represent "timestamp"?

Comment (sergio-mena) [reply state/execution_test.go:209]: Yes. What do you suggest?

Comment (thanethomson) [reply state/execution_test.go]: The linter was recommending `shouldHaveTS`, but any of those should do.

**Review by lasarojc — APPROVED** [review]
