### PR TITLE
v0.37 pubsub: Handle big ints

### LINKED ISSUE #726: Using pubsub query with big values results in an int64 overflow
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): should be latest

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Rebus

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Install tools**:
- **Others**:

**node command runtime flags**:

### What happened?

I am building a tool to subscribe to transactions and messages I need. Internally I use Query /libs/pubsub/query/query.go to filter out messages I do not need. One of my goals is to use values comparison (for example, as in this filter: delegate.amount > 10000000, to filter out MsgDelegate messages with amount less than 10m native tokens). It works okay with small values, but on chains with a different denom exponent (namely, Rebus, with exponent 18, and probably Evmos (haven't tested it with it, but it should result in a similar error)), when trying to subscribe to that filter, it would result in the following error:

```
7:52PM ERR Error querying for events err="failed to match against query message.action = '/cosmos.staking.v1beta1.MsgDelegate' AND delegate.amount > 10000000000000000000: got strconv.ParseInt: parsing \"10000000000000000000\": value out of range while trying to parse 10000000000000000000 as int64 (should never happen if the grammar is correct)" module=pubsub server=node
```

And if you do the same in app (try to create a filter from the following string and use query.Matches() on it, it would result in the error in this app.

### What did you expect to happen?

 Conversion is done without any errors.

### How to reproduce it

- Start a Rebus node (or any other node that has denom exponent 18 or bigger)
- Subscribe via Tendermint Websockets to the updates on the following filter: `message.action = '/cosmos.staking.v1beta1.MsgDelegate' AND delegate.amount > 10000000000000000000`
- Check logs and see errors if such transactions would occur, get a message like the one above per each.

### Logs

See above

### Anything else we need to know

This is a copy of https://github.com/tendermint/tendermint/issues/9978 which was closed as stale but apparently never fixed.

### PR DESCRIPTION
**Pull request by jmalicevic**
Closes #726 for 0.37.x.

This is a draft PR. The main goal is to  make sure that big integers are parsed properly without a loss of precision. Int64 values will be processed as before. 
It also fixes the old logic where ints and floats were treated the same if a float had a fraction due to the fact that the float was converted to an int before comparison. 

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

File: state/indexer/block/kv/kv_test.go [hunk 1]
```diff
@@ -249,26 +249,14 @@ func TestBlockIndexerMulti(t *testing.T) {
 			q:       query.MustParse("block.height = 1"),
 			results: []int64{1},
 		},
-		"query return all events from a height - exact - no match.events": {
```
Comment (jmalicevic) [inline state/indexer/block/kv/kv_test.go:252]: These are just duplicate tests, piggy backing their removal onto this PR. We already did this for 0.38 and main

File: libs/pubsub/query/query_test.go [hunk 2]
```diff
@@ -11,6 +12,47 @@ import (
...
+		matches  bool
+		matchErr bool
+	}{
+
+		{"account.balance <= 10000000000000000000", map[string][]string{"account.balance": {"10000000000000000000"}}, false, true, false},
+		{"account.balance <= 10000000000000000000", map[string][]string{"account.balance": {"10000000000000000000.0"}}, false, true, false},
+		{"account.balance <= 20000000000000000000", map[string][]string{"account.balance": {"10000000000000000000"}}, false, true, false},
+		{"account.balance <= 10000000000000000000", map[string][]string{"account.balance": {"10000000000000000001"}}, false, false, false},
+		{"account.balance <= 10000000000000000002", map[string][]string{"account.balance": {"10000000000000000000.6"}}, false, true, false},
+		{"account.balance > 10000000000000000000", map[string][]string{"account.balance": {"10000000000000000000.6"}}, false, true, false},
```
Comment (lasarojc) [inline libs/pubsub/query/query_test.go:29]: Could you add the following checks for negative values?

```suggestion
		{"account.balance > 10000000000000000000", map[string][]string{"account.balance": {"10000000000000000000.6"}}, false, true, false},
				{"account.balance <= -10000000000000000000", map[string][]string{"account.balance": {"-10000000000000000000"}}, false, true, false},
		{"account.balance <= -10000000000000000000", map[string][]string{"account.balance": {"-10000000000000000000.0"}}, false, true, false},
		{"account.balance <= -20000000000000000000", map[string][]string{"account.balance": {"-10000000000000000000"}}, false, false, false},
		{"account.balance <= -10000000000000000000", map[string][]string{"account.balance": {"-10000000000000000001"}}, false, true, false},
		{"account.balance <= -10000000000000000002", map[string][]string{"account.balance": {"-10000000000000000000.6"}}, false, false, false},
		{"account.balance > -10000000000000000000", map[string][]string{"account.balance": {"-10000000000000000000.6"}}, false, false, false},

```

Comment (sergio-mena) [inline libs/pubsub/query/query_test.go:29]: Does this also pass?
```
{"account.balance > 10000000000000000000", map[string][]string{"account.balance": {"10000000000000000000.1"}}, false, true, false},
```

File: libs/pubsub/query/query_test.go [hunk 3]
```diff
@@ -33,6 +75,7 @@ func TestMatches(t *testing.T) {
 		{"tx.gas > 7 AND tx.gas < 9", map[string][]string{"tx.gas": {"8"}}, false, true, false},
 		{"body.weight >= 3.5", map[string][]string{"body.weight": {"3.5"}}, false, true, false},
 		{"account.balance < 1000.0", map[string][]string{"account.balance": {"900"}}, false, true, false},
+
```
Comment (sergio-mena) [inline libs/pubsub/query/query_test.go:78]: ?

**Review by sergio-mena — APPROVED** [review]
LGTM. I payed a lot of attention, but added some questions on parts I didn't fully understand.

File: libs/pubsub/query/query_test.go [hunk 4]
```diff
@@ -11,6 +12,47 @@ import (
...
+	for _, tc := range testCases {
+		q, err := query.New(tc.s)
+		if !tc.err {
+			require.Nil(t, err)
+		}
+		require.NotNil(t, q, "Query '%s' should not be nil", tc.s)
+
+		if tc.matches {
+			match, err := q.Matches(tc.events)
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply libs/pubsub/query/query_test.go:45]: Weirdly enough, `Conditions()` is called only from the indexer but I could add a few UTs to make sure the conditions are parsed properly.

File: libs/pubsub/query/query.go [hunk 5]
```diff
@@ -452,42 +457,54 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
-		var v int64
+	case reflect.Pointer:
+
+		switch operand.Interface().(type) {
+		case *big.Int:
+			filteredValue := numRegex.FindString(value)
+			operandVal := operand.Interface().(*big.Int)
+			var cmpRes int
+			v := new(big.Int)
+			if strings.ContainsAny(filteredValue, ".") {
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply libs/pubsub/query/query.go:468]: This is the value read from the DB so it could be anything.

File: libs/pubsub/query/query.go [hunk 6]
```diff
@@ -452,42 +457,54 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
 
-	case reflect.Int64:
-		var v int64
+	case reflect.Pointer:
+
+		switch operand.Interface().(type) {
+		case *big.Int:
+			filteredValue := numRegex.FindString(value)
+			operandVal := operand.Interface().(*big.Int)
+			var cmpRes int
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply libs/pubsub/query/query.go:466]: Ah nice catch. This was left over from the previous commit where I had two different cases and called Cmp() in both the if and else so I needed the declaration first. fixed.

File: libs/pubsub/query/query_test.go (hunk 2 above)
Comment (jmalicevic) [reply libs/pubsub/query/query_test.go:29]: No it does not because the `10000000000000000000.1` will be converted to `10000000000000000000.1`.

Comment (jmalicevic) [reply libs/pubsub/query/query_test.go]: Looking at the error I get when I run this and at the rules of the [query grammar](https://github.com/cometbft/cometbft/blob/jasmina/726-pubsub-int-overflow/libs/pubsub/query/query.peg), it seems that negative numbers in the query are not allowed.

File: state/indexer/query_range.go [hunk 7]
```diff
@@ -44,6 +45,9 @@ func (qr QueryRange) LowerBoundValue() interface{} {
 	switch t := qr.LowerBound.(type) {
 	case int64:
 		return t + 1
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply state/indexer/query_range.go:47]: I thought it was needed for the height but no, you are right, we always call this with a bigInt.

File: libs/pubsub/query/query_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (jmalicevic) [reply libs/pubsub/query/query_test.go:50]: Added new tests specifically for this.

File: libs/pubsub/query/query_test.go (hunk 2 above)
Comment (jmalicevic) [reply libs/pubsub/query/query_test.go]: I will bring this up on Monday, it seems that the DB allows event values to be stored  as floats. But the indexer queries always get the event value and convert it an int. So you end up with this particular event not being detected. 
We can leave this behaviour for old versions but it feels incorrect. Converting to int might work for most cases but in this particular cases, we need to detect that this number is a float, then parse it and check that there is a decimal part if the non decimal part is the same. I think for main we should 100% do this. But I want us to reach consensus on whether we want to do this for 0.34/0.37

Comment (lasarojc) [reply libs/pubsub/query/query_test.go]: Thanks for checking. Indeed it does not seem like it. There is no limitation on the data itself, right? Is this a bug?

Comment (jmalicevic) [reply libs/pubsub/query/query_test.go]: You are right, you could technically submit anything as a tx event I believe. But querying is not supported. I am not sure tbh...in does seem wrong to disable querying something that can be provided as input :/

Comment (sergio-mena) [reply libs/pubsub/query/query_test.go]: From today's discussion, I understand that [my initial comment](https://github.com/cometbft/cometbft/pull/771#discussion_r1180588069) does not apply to `v0.37.x`/`v0.34.x` (which this PR is targeting), isn't it?

Comment (jmalicevic) [reply libs/pubsub/query/query_test.go]: Reverting this commit means that if there is a float in the DB, it will be converted to its value in int64.

File: state/indexer/block/kv/kv.go [hunk 8]
```diff
@@ -293,10 +294,17 @@ LOOP:
...
+			v := new(big.Int)
+			v, ok := v.SetString(eventValue, 10)
+			if !ok {
+
+				v_f, err := strconv.ParseFloat(eventValue, 64)
+				if err != nil {
+					continue LOOP
+				}
+				v = new(big.Int)
+				v = v.SetInt64(int64(v_f))
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:307]: Two questions:
1) This part was not present in the original. Do we need it?
2) Should `ParseFloat` be replaced by a bog float?

Comment (jmalicevic) [reply state/indexer/block/kv/kv.go:307]: Hey, no it was not, this case basically covers the functionality we discussed today that we decided to ignore. This is when an event is stored in the DB as a float and it will not be parsed as BigInt (the `ok` in line 298 will be false). To mimic the original behaviour in 0.34 (before introducing BigInts), we need to still somehow parse the float into at least the int64. This same reasoning applies to the change in [this part ](https://github.com/cometbft/cometbft/blob/1dd27a7cb11df703065a29b173ed53b2e3cd374e/libs/pubsub/query/query.go#L476)of the code . Note that there I do use a big float. And I am actually considering now what the best approach is. Because using the BigFloat used in `query.go` rounds the float (which is not done with a simple cast of float64 to int64), but using a simple cast will not parse BigFloats and ints properly. Trying to find a solution and will mark the PR as draft and re-open it to avoid confusion.

Comment (sergio-mena) [reply state/indexer/block/kv/kv.go]: I think what you suggested in slack would be the simplest (to be consistent with the current behavior in `v0.34.x`/`v0.37.x`): if there is a dot, just split the string and use the whole number part

File: state/indexer/block/kv/kv.go [hunk 9]
```diff
@@ -294,17 +295,21 @@ LOOP:
...
 		}
 
-		if _, ok := qr.AnyBound().(*big.Int); ok { // This means that in a range we can only have integers, floats will be ignored
+		if _, ok := qr.AnyBound().(*big.Int); ok {
 			v := new(big.Int)
 			v, ok := v.SetString(eventValue, 10)
-			if !ok {
-
-				v_f, err := strconv.ParseFloat(eventValue, 64)
+			if !ok { // If the number was not int it will might be a float so we get the int value
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:301]:
```suggestion
			if !ok { // If the number was not int it might be a float so we get the int value
```

File: libs/pubsub/query/query.go [hunk 10]
```diff
@@ -452,42 +457,57 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
-		operandInt := operand.Interface().(int64)
-		filteredValue := numRegex.FindString(value)
+		switch operand.Interface().(type) {
+		case *big.Int:
+			filteredValue := numRegex.FindString(value)
+			operandVal := operand.Interface().(*big.Int)
+			v := new(big.Int)
+			if strings.ContainsAny(filteredValue, ".") {
+				// We do this just to check whether the string can be parsed as a float
+				_, err := strconv.ParseFloat(filteredValue, 64)
```
Comment (sergio-mena) [inline libs/pubsub/query/query.go:469]: What if we get a very big float (e.g., 600000000000000000000000000000000000000000000000000000001), shouldn't we still parse it as a BigFloat (to make sure we don't lose the last 1) ?

File: libs/pubsub/query/query.go [hunk 11]
```diff
@@ -452,42 +457,57 @@ func matchValue(value string, op Operator, operand reflect.Value) (bool, error)
...
-			v1, err := strconv.ParseFloat(filteredValue, 64)
-			if err != nil {
-				return false, fmt.Errorf("failed to convert value %v from event attribute to float64: %w", filteredValue, err)
-			}
+				// If yes, we get the int part of the  string.
+				// We could simply cast the float to an int and use that to create a big int but
+				// if it is a number bigger than int64, it will not be parsed properly.
+				// If we use bigFloat and convert that to a string, the values will be rounded which
+				// is not what we want either.
+				_, ok := v.SetString(strings.Split(filteredValue, ".")[0], 10)
```
Comment (sergio-mena) [inline libs/pubsub/query/query.go:483]: Suggestion: I'd add something like "we are simulating int64(v1), which was here before this patch"

File: .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md [hunk 12]
```diff
@@ -0,0 +1,3 @@
+- `[state/kvindex]` Querying event attributes that are bigger than int64 is now enabled as well as properly converting float event values 
+from the database into int64 values ,even if the float is bigger than an int64.
```
Comment (lasarojc) [inline .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md:2]:
```suggestion
from the database into int64 values, even if the float is bigger than an int64. 
```

**Review by lasarojc — APPROVED** [review]

File: state/indexer/query_range.go [hunk 13]
```diff
@@ -67,7 +69,9 @@ func (qr QueryRange) UpperBoundValue() interface{} {
 	switch t := qr.UpperBound.(type) {
 	case int64:
 		return t - 1
-
+	case *big.Int:
```
Comment (sergio-mena) [inline state/indexer/query_range.go:72]: (from sync discussion) Do we need to delete 70-71 to be consistent with `LowerBoundValue`

Comment (jmalicevic) [reply state/indexer/query_range.go:72]: Reverted the deletion in `LowerBoundValue`

**Review by sergio-mena — APPROVED** [review]
🥳

File: libs/pubsub/query/query.go [hunk 14]
```diff
@@ -152,16 +153,18 @@ func (q *Query) Conditions() ([]Condition, error) {
...
-				if err != nil {
-					err = fmt.Errorf(
-						"got %v while trying to parse %s as int64 (should never happen if the grammar is correct)",
-						err, number,
+				valueBig := new(big.Int)
+
+				valueBig, ok := valueBig.SetString(number, 10)
+				if !ok {
+					err := fmt.Errorf(
+						"problem parsing %s as bigint (should never happen if the grammar is correct)",
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply libs/pubsub/query/query.go:161]: As this is the default message in a bunch of other places and it actually makes sense - comparing the query to the query grammar, I would leave this?
