### PR TITLE
pruning:do not attempt to prune state if no blocks are pruned

### LINKED ISSUE #1615: pruning: Should not attempt to prune state store if no blocks were pruned
### Setup

**CometBFT version** 

main; v0.38.x-experimental 

**Have you tried the latest version**: yes/no
yes 

### Config

Pruning is enabled. 

### What happened?

In the extreme case where pruning is  triggered while the chain is at height 1 and the retain height is set to 1, no blocks can be pruned as they should not be. However, we still attempt to prune the state store and get an error that pruning failed. 

### What did you expect to happen?

If not blocks are pruned, there should be no attempt to prune the states. 

### How to reproduce it

The bug appeared in subsequent runs of the `TestProvider` test in `http_test`. The test added with the fix would fail if not for the changes fixing it.

### PR DESCRIPTION
**Pull request by jmalicevic**
Closes #1615 

Needs a backport to 0.38.x-experimental

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments - **not needed**

### CODE REVIEW

File: state/export_test.go [hunk 1]
```diff
@@ -64,6 +64,10 @@ func (p *Pruner) PruneBlockIndexerToRetainHeight(lastRetainHeight int64) int64 {
 	return p.pruneBlockIndexerToRetainHeight(lastRetainHeight)
 }
 
+func (p *Pruner) PruneBlocksToHeight(height int64) (uint64, int64, error) {
```
Comment (mzabaluev) [inline state/export_test.go:67]: Just rename the private method?

**Review by mzabaluev — APPROVED** [review]

**Review by melekes — APPROVED** [review]
👍

**Comment by lasarojc** [comment]
Blocked by #1619

File: state/export_test.go (hunk 1 above)
Comment (jmalicevic) [reply state/export_test.go:67]: @thanethomson , @mzabaluev , we used to favor this approach as to avoid exposing functions that we use internally if they are exposed just for testing. I don't mind altering the code but want to make sure we are all on the same page.

Comment (thanethomson) [reply state/export_test.go]: Ah I see. Yes @mzabaluev if it's just exposed for testing purposes, we basically create a public wrapper method in a `_test.go` file. These `_test.go` files are not built when building the binary, but are built when running tests.

**Review by thanethomson — APPROVED** [review]
