### PR TITLE
fix(crypto): panic: encoding: unsupported key {0xc015dcc0c0}

### LINKED ISSUE #3699: panic: encoding: unsupported key {0xc015dcc0c0}
```
validator04  | panic: encoding: unsupported key {0xc015dcc0c0}
validator04  | 
validator04  | goroutine 1 [running]:
validator04  | github.com/cometbft/cometbft/types.(*Validator).Bytes(0xc0001813c0)
validator04  | 	github.com/cometbft/cometbft/types/validator.go:126 +0x8b
validator04  | github.com/cometbft/cometbft/types.(*ValidatorSet).Hash(0xc015db2a50)
validator04  | 	github.com/cometbft/cometbft/types/validator_set.go:368 +0x76
validator04  | github.com/cometbft/cometbft/types.LightBlock.ValidateBasic({0xc0000da7f8?, 0xc015db2a50?}, {0xc00025be20?, 0xc015daa440?})
validator04  | 	github.com/cometbft/cometbft/types/light.go:37 +0xf7
validator04  | github.com/cometbft/cometbft/light/provider/http.(*http).LightBlock(0xc000040380, {0x1998fe0, 0xc00015e1c0}, 0x1)
validator04  | 	github.com/cometbft/cometbft/light/provider/http/http.go:96 +0x1fb
validator04  | github.com/cometbft/cometbft/light.(*Client).lightBlockFromPrimary(0xc0003a2780, {0x1998fe0, 0xc00015e1c0}, 0x1)
validator04  | 	github.com/cometbft/cometbft/light/client.go:991 +0x7f
validator04  | github.com/cometbft/cometbft/light.(*Client).initializeWithTrustOptions(0xc0003a2780, {0x1998fe0, 0xc00015e1c0}, {0x2260ff9290000, 0x1, {0xc0005d59c0, 0x20, 0x40}})
validator04  | 	github.com/cometbft/cometbft/light/client.go:363 +0x65
validator04  | github.com/cometbft/cometbft/light.NewClient({0x1998fe0, 0xc00015e1c0}, {0xc00025be20?, 0x7fb6023494c8?}, {0x2260ff9290000, 0x1, {0xc0005d59c0, 0x20, 0x40}}, {0x19936e0, ...}, ...)
validator04  | 	github.com/cometbft/cometbft/light/client.go:201 +0x31d
validator04  | github.com/cometbft/cometbft/statesync.NewLightClientStateProviderWithDBKeyVersion({0x1998fe0, 0xc00015e1c0}, {0xc00025be20, 0x10}, {{0x13c65d0?, 0xc0001db5e8?}, {0x16911bd?, 0x0?}}, 0x1, {0xc00023c090, ...}, ...)
validator04  | 	github.com/cometbft/cometbft/statesync/stateprovider.go:74 +0x69e
validator04  | github.com/cometbft/cometbft/node.startStateSync(_, {_, _}, {_, _}, _, {_, _}, _, {{{0xb, ...}, ...}, ...}, ...)
validator04  | 	github.com/cometbft/cometbft/node/setup.go:573 +0x29a
validator04  | github.com/cometbft/cometbft/node.(*Node).OnStart(0xc00054e008)
validator04  | 	github.com/cometbft/cometbft/node/node.go:637 +0x5e5
validator04  | github.com/cometbft/cometbft/libs/service.(*BaseService).Start(0xc00054e008)
validator04  | 	github.com/cometbft/cometbft/libs/service/service.go:146 +0x2f5
validator04  | github.com/cometbft/cometbft/cmd/cometbft/commands.NewRunNodeCmd.func1(0xc0004efb08?, {0x2514e20?, 0x0?, 0x0?})
validator04  | 	github.com/cometbft/cometbft/cmd/cometbft/commands/run_node.go:108 +0x98
validator04  | github.com/spf13/cobra.(*Command).execute(0xc0004efb08, {0x2514e20, 0x0, 0x0})
validator04  | 	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
validator04  | github.com/spf13/cobra.(*Command).ExecuteC(0x2432420)
validator04  | 	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
validator04  | github.com/spf13/cobra.(*Command).Execute(...)
validator04  | 	github.com/spf13/cobra@v1.8.1/command.go:1041
validator04  | github.com/cometbft/cometbft/libs/cli.Executor.Execute({0x2432420?, 0x180a878?})
validator04  | 	github.com/cometbft/cometbft/libs/cli/setup.go:89 +0x45
validator04  | main.main()
validator04  | 	github.com/cometbft/cometbft/cmd/cometbft/main.go:51 +0x20a
```

https://github.com/cometbft/cometbft/actions/runs/10380297721/job/28739885975

### PR DESCRIPTION
**Pull request by melekes**
Closes #3699

---

#### PR checklist

- [ ] ~~Tests written/updated~~
- [ ] ~~Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

File: types/validator.go [hunk 1]
```diff
@@ -123,7 +123,9 @@ func ValidatorListString(vals []*Validator) string {
 func (v *Validator) Bytes() []byte {
 	pk, err := ce.PubKeyToProto(v.PubKey)
 	if err != nil {
-		panic(err)
+		// Unsupported key.
+		// Since this is used by the light client, we should not panic here.
```
Comment (melekes) [inline types/validator.go:127]: Is this clear enough?

**Comment by melekes** [comment]
#go-api-breaking

File: crypto/encoding/codec.go [hunk 2]
```diff
@@ -57,9 +59,9 @@ func PubKeyToProto(k crypto.PubKey) (pc.PublicKey, error) {
 				Secp256K1: k,
 			},
 		}
-	case *bls12381.PubKey:
+	case *bls12381.PubKey, bls12381.PubKey:
```
Comment (sergio-mena) [inline crypto/encoding/codec.go:62]: Do we need to keep the `*bls12381.PubKey`?
The declaration in the method is clearly not a pointer

File: types/validator.go [hunk 3]
```diff
@@ -120,10 +120,14 @@ func ValidatorListString(vals []*Validator) string {
 // These are the bytes that gets hashed in consensus. It excludes address
 // as its redundant with the pubkey. This also excludes ProposerPriority
 // which changes every round.
+//
+// If the public key is unsupported, it returns nil.
```
Comment (sergio-mena) [inline types/validator.go:124]:
```suggestion
// If the public key is unsupported, it returns nil. Caller must handle `nil` as it would handle an error
```

File: types/validator.go (hunk 1 above)
Comment (sergio-mena) [reply types/validator.go:129]: I added a suggestion above

File: crypto/encoding/codec.go (hunk 2 above)
Comment (melekes) [reply crypto/encoding/codec.go:62]: The declaration in the method is an interface.

Comment (sergio-mena) [reply crypto/encoding/codec.go:62]: Yeah, so if it's an interface, does it make sense to leave `*bls12381.PubKey` (a pointer to an interface)?

Comment (melekes) [reply crypto/encoding/codec.go:62]: `*bls12381.PubKey` is a pointer to a struct. I would leave both (a pointer to a struct and struct itself) to be safe

Comment (sergio-mena) [reply crypto/encoding/codec.go:62]: OK, fair enough. Approving

**Review by sergio-mena — APPROVED** [review]

File: crypto/encoding/codec.go (hunk 2 above)
Comment (andynog) [reply crypto/encoding/codec.go:62]: I couldn't find a case where a concrete type `bls12381.PubKey` would make into this method based on the current implementation.

Another approach would be to have used the same as in `PubKeyFromTypeAndBytes` leveraging the `k.Type()` something like

```
	switch k.Type() {
	case bls12381.KeyType:
		//...
	} 
```

**Review by andynog — COMMENTED** [review]
made comments

File: types/validator.go [hunk 4]
```diff
@@ -120,10 +120,15 @@ func ValidatorListString(vals []*Validator) string {
...
+//
+// If the public key is unsupported, it returns nil. Caller must handle `nil`
+// as it would handle an error.
 func (v *Validator) Bytes() []byte {
 	pk, err := ce.PubKeyToProto(v.PubKey)
 	if err != nil {
-		panic(err)
+		// Unsupported key.
+		// Since this is used by the light client, we should not panic here.
+		return nil
```
[the remark this answers is not in the document]
Comment (melekes) [reply types/validator.go:131]: > Should we add a changelog entry? Not sure if this behavior change would be considered breaking but if we are expecting now the caller to handle a nil return probably a good idea to have at least an entry to highlight that?

I consider this change too minor to add a changelog entry.

> also, do we have to change the code anywhere to handle a nil return?

Nope.

File: crypto/encoding/codec.go (hunk 2 above)
Comment (melekes) [reply crypto/encoding/codec.go:62]: > Another approach would be to have used the same as in PubKeyFromTypeAndBytes leveraging the k.Type() something like

Great idea!
